spring:
  kafka:
    bootstrap-servers: pkc-oxqxx9.us-east-1.aws.confluent.cloud:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="QNBVJUMU7C7U5OMY" password="cfltfeA1PDCKEinykxYIl24p0Xnng3lBZs3Dwf2eGVI9JJQDyBpiw2oyh8HrZQwQ";

app:
  kafka:
    topic:
      scorecard-request: scorecard-request-events